# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics



on:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 * * 3"
  push:
    branches:
      - "master"
      - "main"



jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: aleroxac
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          plugin_habits: no
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 10
          plugin_habits_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_notable: no
          plugin_notable_from: organization
          plugin_notable_types: commit

          plugin_people: no
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
